version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress-site-manager

  wordpress:
    image: wordpress:latest
    links:
      - db
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html/wp-content/plugins/site-manager
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
    networks:
      - wordpress-site-manager


networks:
  wordpress-site-manager:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
          gateway: 192.168.3.1
